apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-search-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: product-search
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: api-port
    path: /metrics
    interval: 15s