apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-search-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack # IMPORTANT: Must match the Helm release name label
spec:
  selector:
    matchLabels:
      app: product-search # Matches your Service label
  namespaceSelector:
    matchNames:
      - default # Assuming your app is in the 'default' namespace
  endpoints:
  - port: api-port
    path: /metrics
    interval: 15s